docs: added example in docs of using a resolver for metatags for markdown component (#1014)
analogjs/analog pull request #1082
Opened 2024-05-03 23:42 UTC by AmGarera

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [x] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #1014 

## What is the new behavior?

A new Example added to the docs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-05-06 14:47 UTC, brandonroberts requested changes

2024-05-06 14:47 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +The `postMetaResolver` function is responsible for fetching the meta tags for a post. This function should return an array of meta tags. Here's an example:
```suggestion
In your route configuration, you can use the `RouteMeta` object to resolve meta tags for a route. This is done by assigning the `postMetaResolver` function to the `meta` property. 

Below is an example of using a `postMetaResolver` function that fetches the meta tags for a post. This function returns an array of meta tags.
```

2024-05-06 14:47 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +  readonly metaTags$ = this.route.data.pipe(pluck('meta'));
Isn't `pluck` deprecated in RxJS?

```suggestion
  readonly metaTags$ = this.route.data.pipe(map(data => data['meta']));
```

2024-05-06 14:47 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +  <analog-markdown [content]="post.content" [metaTags]="metaTags$ | async"></analog-markdown>
```suggestion
  <my-component [metaTags]="metaTags$ | async"></my-component>
```

2024-05-06 14:47 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +The `MarkdownComponent` should be modified to accept an input for meta tags and use these when rendering the markdown content. Here's an example:
I think this section should be removed

2024-05-20 16:51 UTC, brandonroberts commented
@AmGarera are you still interested in landing these changes?

2024-05-20 16:53 UTC, AmGarera commented
Yeah I should get sometime later today to address your requested changes.

2024-05-20 23:30 UTC, AmGarera commented on apps/docs-app/docs/features/routing/content.md
> +  readonly metaTags$ = this.route.data.pipe(pluck('meta'));
Yup as of RxJS 7 it is

2024-05-20 23:33 UTC, AmGarera commented on apps/docs-app/docs/features/routing/content.md
> +The `MarkdownComponent` should be modified to accept an input for meta tags and use these when rendering the markdown content. Here's an example:
Removed as requested

2024-05-21 01:06 UTC, brandonroberts approved these changes

2024-05-21 01:06 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +````
```suggestion
```
```

2024-05-21 02:26 UTC, merged

2024-05-21 02:27 UTC, brandonroberts commented
Thanks! @allcontributors add @AmGarera for doc