282 content files with prefix
analogjs/analog pull request #286
Opened 2023-03-02 19:12 UTC by BaronVonPerko

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-angular-plugin
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [x] content

## What is the current behavior?

The current `injectContent()` does not support subdirectories within the **content** folder.

Issue Number: #282 

## What is the new behavior?

This allows the existing string parameter for the routeParam to remain the same, but also allows the developer to pass in an object instead, consisting of the routeParam key as well as the subdirectory name.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-03-02 23:32 UTC, brandonroberts requested changes

2023-03-02 23:32 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/content.md
> +```ts
Using a treeview would fit better here. Example below

```treeview
src/
└── app/
    └── routes/
        │   └── products/
        │      ├──[productId].ts
        │      └──(products-list).ts
        └── products.ts
```

2023-03-03 20:41 UTC, BaronVonPerko commented on apps/docs-app/docs/features/routing/content.md
> +```ts
Updated 👍🏻

2023-03-03 23:07 UTC, brandonroberts approved these changes
LGTM

2023-03-03 23:08 UTC, merged

2023-03-03 23:08 UTC, brandonroberts commented
Awesome! @allcontributors add @BaronVonPerko for code,doc