DRAFT: feat(trpc): add rxjs observable compatible trpc client #379
analogjs/analog pull request #385
Opened 2023-05-11 13:53 UTC by Dafnik

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [X] trpc

## What is the current behavior?

Current trpc client only works with `Promises`

Issue Number: 379

## What is the new behavior?

This new client works with RxJS Observables.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

2023-05-12 18:07 UTC, goetzrobin commented
Wow thanks so much for adding all that!

I would almost say that instead of creating a new separate tRPC client and e2e project you can simply replace the existing Promise based client with the Observable one. I know this is a breaking change, but I think we are early enough to introduce it.

I think it is worth it, because the observable client fits so much better into the Angular ecosystem.

I also know that this would mean we'd have to adjust the templates of the nx-plugin, but that should be pretty straight forward. (I can obviously help with that too!)

Open to discuss of course. @brandonroberts @Dafnik what do you think?

2023-05-15 23:32 UTC, goetzrobin commented
@brandonroberts @Dafnik  Another thing that might be worth considering to add in the scope of this is adding support for authentication. The issue I created for that is here: https://github.com/analogjs/analog/issues/394 
I think the low hanging fruit is just allow the tRPC client to take in all params that httpBatchLink takes.

2023-05-16 13:29 UTC, brandonroberts commented
I agree. Let's land the observable compatible version first as signals are still in developer preview. Then we can revisit signal support later. Same with adding auth in a separate PR.


Thanks for working on this! 

@goetzrobin if you're good on the review, lets move to merge

2023-05-16 13:32 UTC, goetzrobin commented
@brandonroberts we will replace the current promise based implementation with @Dafnik 's RxJs version. I will review the PR once he pushes the new changes and merge them once everything looks good 👍

2023-05-17 12:23 UTC, goetzrobin requested changes
Awesome work! I left a couple comments, mostly just formatting stuff. 

The thing about transferStateLink not being used is a bit of a headscratcher for me right now, but I think we could live without the caching for now and revisit in a new PR, unless it's an easy fix for you...

Thanks so much for working on this! This will be an awesome addition!

2023-05-17 12:45 UTC, Dafnik commented on apps/trpc-app/src/app/app.component.ts
> +import { RouterOutlet } from "@angular/router";
Hey, sorry about all the importing errors. I actually run prettier before committing but I think my IDE messed with them. I will definitely fix this.

2023-05-17 12:45 UTC, Dafnik commented on packages/trpc/src/lib/client/client.ts
> +  options: Partial<CreateTRPCClientOptions<T>>;
Nop, just a copying error.

2023-05-17 12:47 UTC, Dafnik commented on packages/trpc/src/lib/client/shared-internal.ts
> +} from "@trpc/server";
This is actually I would like to work on next.

There is some tooling stuff in this repository I'd like to improve. Like migrating to pnpm, some githooks which could be simplified and some additional and updated actions to check for formatting etc.

2023-05-17 13:38 UTC, Dafnik commented on apps/trpc-app/src/app/pages/index.page.ts
> +  public triggerRefresh$ = new BehaviorSubject(true);
Hi, I've also just looked into this. I've added a log line in line `52` of `transfer-link-state.ts`. the `trpc.note.list.query()` is run two times and on the second run `isCacheActive.getValue()` is `false`.

Thanks for the link!

2023-05-17 13:39 UTC, Dafnik commented on packages/trpc/src/lib/client/client.ts
> +  options: Partial<CreateTRPCClientOptions<T>>;
Yeah, I was working on the other stuff too. haha but thx

2023-05-17 13:41 UTC, Dafnik commented on apps/trpc-app/src/app/pages/index.page.ts
> +  public triggerRefresh$ = new BehaviorSubject(true);
You are right, it looks like it has something to do with the transfer cache active subject.

2023-05-17 15:18 UTC, goetzrobin commented on apps/trpc-app/src/app/pages/index.page.ts
> +  public triggerRefresh$ = new BehaviorSubject(true);
I vaguely remember there being a reason why I did it that way, but I am not completely sure anymore...

I think the subscription through `notes$ | async` in the template might be after the app already stabilized and therefore is after the cache is active

2023-05-17 18:51 UTC, goetzrobin approved these changes

2023-05-17 18:53 UTC, merged

2023-05-18 10:22 UTC, Dafnik commented on apps/trpc-app/src/app/pages/index.page.ts
> +  public triggerRefresh$ = new BehaviorSubject(true);
Hi, yeah, everything was already done! Just didn't get to reply you yet but thank you for reviewing and merging everything!

2023-05-18 10:23 UTC, Dafnik commented
It was my pleasure @goetzrobin! Thanks for doing all of this work and I would love to also help out in the future.