docs: fix styling for buttons on mobile
analogjs/analog pull request #42
Opened 2022-08-18 19:05 UTC by dalenguyen

**References**
- Closes #38 

**New Behaviour**

![image](https://user-images.githubusercontent.com/14116156/185473920-cc9b2f8f-9ca2-42c7-9d2e-489b6523ee81.png)

2022-08-18 19:07 UTC, dalenguyen commented
@brandonroberts @LayZeeDK I'm utilizing `margin-bottom--md (1rem)` from infima & `flex-wrap` to push the button down on mobile devices. Please let me know if this approach works.

2022-08-18 20:09 UTC, LayZeeDK commented
Good solution, @dalenguyen.

I wonder how it looks if we make those CTA button links full width on small screens 🤔

2022-08-18 20:38 UTC, dalenguyen commented
@LayZeeDK I can target the a tag on smaller screens and make the button full with this 

```
@media screen and (max-width: 562px) { 
  .buttons a {
    flex: 1;
    display: flex;
    justify-content: center;
  }
}
```

Then on a smaller screen, it will look like this 

![image](https://user-images.githubusercontent.com/14116156/185490125-266bb166-c98b-4752-8c76-529a7c247e5e.png)

2022-08-18 21:31 UTC, LayZeeDK commented
Infima/Docusaurus uses a breakpoint, I belive it is 996px width.

2022-08-18 21:32 UTC, LayZeeDK commented
Visually it looks great though!

2022-08-19 00:19 UTC, brandonroberts commented
I like the full width buttons also!

2022-08-19 01:58 UTC, dalenguyen commented
@LayZeeDK I saw that they implement `576px & 996px` as breakpoints on their styling. Using `576px` makes more sense since having full with buttons on top of each other at `996px` is a bit much. What do you think?

2022-08-19 04:38 UTC, LayZeeDK commented
Makes sense!

2022-08-19 04:40 UTC, LayZeeDK commented
Add the full width style to the home page and we're good to go in my opinion 😊

2022-08-19 11:34 UTC, dalenguyen commented
Cool. Just applied full width to buttons on mobile :D

2022-08-19 13:15 UTC, LayZeeDK requested changes

2022-08-19 13:15 UTC, LayZeeDK commented on apps/docs-app/src/pages/index.module.css
> +  gap: 1rem;
praise: Great solution!

2022-08-19 13:15 UTC, LayZeeDK commented on apps/docs-app/src/pages/index.module.css
> +  gap: 1rem;
issue: Use the Infima spacing variable instead of hard-coding `1rem`.
```suggestion
  gap: var(--ifm-global-spacing);
```

2022-08-19 17:19 UTC, brandonroberts approved these changes
LGTM

2022-08-19 17:19 UTC, merged

2022-08-19 17:20 UTC, brandonroberts commented
Thanks Dale! @allcontributors Please add @dalenguyen for css

2022-08-19 17:21 UTC, brandonroberts commented
Ok lol. @allcontributors Please add @dalenguyen for design