feat(nx-plugin): update version handling for Nx 16.4 and parameterize…
analogjs/analog pull request #481
Opened 2023-06-25 03:09 UTC by jeremyhofer

… welcome component

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

2023-06-30 14:15 UTC, goetzrobin requested changes
I tested it locally and we need one more change to make it work for Nx 15:

Where we add the analog dependencies we also need to remove the initially installed
platform version. This is kind of counter intuitive, but we are basically replacing the latest
platform with the one that works for the Nx workspace version. If we don't do that the newest plugin will kept and we get a file path error. Making this changes will take care of the file
changes in the angular builder.

```ts
import { addDependenciesToPackageJson, removeDependenciesFromPackageJson, Tree } from '@nx/devkit';
import { getAnalogDependencies } from '../versions/dependencies';
import { getAnalogDevDependencies } from '../versions/dev-dependencies';

export async function addAnalogDependencies(
  tree: Tree,
  nxVersion: string,
  angularVersion: string
) {
  const dependencies = getAnalogDependencies(nxVersion, angularVersion);
  const devDependencies = getAnalogDevDependencies(nxVersion);
  removeDependenciesFromPackageJson(tree, [], ['@analogjs/platform'])
  addDependenciesToPackageJson(tree, dependencies, devDependencies);
}
```

Another thing I noticed is that I don't believe Nx follows their own version matrix. Once I have Nx 16.0.0 Angular 16.1 gets installed (with a brand new workspace)

2023-07-01 02:30 UTC, goetzrobin approved these changes
Very excited for this to land! 🚀 🔥

2023-07-01 02:32 UTC, goetzrobin commented
@brandonroberts code changes look good from my side and locally tests pass for me. not sure why CI is timing out :(

2023-07-01 03:46 UTC, brandonroberts approved these changes

2023-07-01 03:47 UTC, merged

2023-07-01 03:47 UTC, brandonroberts commented
Awesome work! @allcontributors add @jeremyhofer for code, infra