Q/feature/implement sitemap generator
analogjs/analog pull request #497
Opened 2023-07-03 03:47 UTC by QuantariusRay

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [x] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [x] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

[add sitemap generation support
](https://github.com/analogjs/analog/issues/307)Closes #

## What is the new behavior?

Added a config property in pre-render (though, now, that could probably change in the end). This ends up being a property that is just used to generate the domain name needed... I'm open to changing that to a top-level property, I think it'll make more sense.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) 
https://giphy.com/clips/niallhoran-niall-horan-heartbreak-weather-YlNVZC589alBV7IQ6t

2023-07-03 16:33 UTC, brandonroberts requested changes
Nice work! Minor changes

2023-07-03 16:33 UTC, brandonroberts commented on apps/blog-app/vite.config.ts
> +            domain: 'example.com/',
nit: use the deployment URL

```suggestion
            domain: 'https://analog-blog.netlify.app/',
```

2023-07-03 16:33 UTC, brandonroberts commented on packages/vite-plugin-nitro/src/lib/build-sitemap.ts
> +      page: `https://www.${sitemapConfig.domain}${page.replace(/^\/+/g, '')}`,
Let the user customize the entire host, for example `https://myblog.dev`

```suggestion
      page: `${sitemapConfig.host}${page.replace(/^\/+/g, '')}`,
```

2023-07-03 16:33 UTC, brandonroberts commented on apps/analog-app/vite.config.ts
> +            domain: 'example.com/',
Use the custom base URL for this example

```suggestion
            domain: process.env['VITE_ANALOG_PUBLIC_BASE_URL'],
```

2023-07-03 16:33 UTC, brandonroberts commented on package.json
> +    "xmlbuilder2": "^3.0.2"
This needs to be added to the `dependencies` in `packages/platform/package.json` also

2023-07-03 16:33 UTC, brandonroberts commented on packages/vite-plugin-nitro/src/lib/options.ts
> +  domain: string;
```suggestion
  host: string;
```

2023-07-03 16:33 UTC, brandonroberts commented on packages/vite-plugin-nitro/src/lib/build-sitemap.ts
> +      config.root!,
Let's add a fallback root

```suggestion
      config.root || '.',
```

2023-07-03 16:33 UTC, brandonroberts commented on packages/vite-plugin-nitro/src/lib/build-sitemap.ts
> +import { SitemapConfig } from './options';
nit: put local imports last

```suggestion
import { SitemapConfig } from './options';
```

2023-07-04 00:06 UTC, QuantariusRay commented
Thanks for the review. Made requested changes.

2023-07-04 01:42 UTC, brandonroberts approved these changes

2023-07-04 02:18 UTC, merged

2023-07-04 02:18 UTC, brandonroberts commented
Thanks! @allcontributors add @QuantariusRay for code