docs(astro-angular): describe config to transform external package
analogjs/analog pull request #538
Opened 2023-07-11 12:09 UTC by marcjulian

when using `client:load`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [x] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Documenting #537

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

2023-07-11 22:57 UTC, brandonroberts requested changes

2023-07-11 22:57 UTC, brandonroberts commented on packages/astro-angular/README.md
> +In case you receive an error in development and build when using an Angular component with an external package and in combination with an Astro Client Directive such as `client:load`.
```suggestion
To ensure Angular libraries are transformed during Astro's SSR process, add them to the `ssr.noExternal` array in the Vite config.
```

2023-07-11 22:57 UTC, brandonroberts commented on packages/astro-angular/README.md
> +One option is to add the package(s) to Vite `ssr.noExternal` config.
```suggestion
```

2023-07-12 12:48 UTC, marcjulian commented
Thanks for your review.

2023-07-12 13:54 UTC, brandonroberts commented
Thanks @marcjulian. Will you run `prettier` to format the files. Everything else looks good

2023-07-12 14:03 UTC, marcjulian commented
Of course!

2023-07-12 14:15 UTC, brandonroberts approved these changes

2023-07-12 14:15 UTC, merged