docs(router): add guide for nested redirect routes
analogjs/analog pull request #552
Opened 2023-07-21 15:01 UTC by markostanimirovic

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [x] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-07-21 15:30 UTC, goetzrobin reviewed
Left a couple suggestions! Just minor wording and I wanted to add a note that for nested redirects you will need an absolute path.

2023-07-21 15:30 UTC, goetzrobin commented on apps/docs-app/docs/features/routing/metadata.md
>  Routes can be defined for only the purpose of redirecting to another route.
```suggestion
Routes can be defined for the sole purpose of redirecting to another route.
```

2023-07-21 15:30 UTC, goetzrobin commented on apps/docs-app/docs/features/routing/metadata.md
> +The example above is a redirect to the `/home` route from `/` route.
```suggestion
The example above is a redirect from the `/` route to the `/home` route.
```

2023-07-21 15:30 UTC, goetzrobin commented on apps/docs-app/docs/features/routing/metadata.md
> +and the `routeMeta` definition in the `src/app/pages/cities/index.page.ts` file:
```suggestion
and the following `routeMeta` definition to the `src/app/pages/cities/index.page.ts` file:
```

2023-07-21 15:30 UTC, goetzrobin commented on apps/docs-app/docs/features/routing/metadata.md
> +navigating to `/cities` will redirect to `/cities/new-york`.
```suggestion
Now, navigating to `/cities` will redirect to `/cities/new-york`. 
One final note: Nested redirects always require an absolute path.
```

2023-07-21 16:30 UTC, goetzrobin approved these changes

2023-07-21 16:35 UTC, brandonroberts requested changes

2023-07-21 16:35 UTC, brandonroberts commented on apps/docs-app/docs/features/routing/metadata.md
> +navigating to `/cities` will redirect to `/cities/new-york`.
```suggestion
Navigating to `/cities` redirects to `/cities/new-york`.
```

2023-07-22 19:50 UTC, brandonroberts approved these changes

2023-07-22 19:50 UTC, merged