feat(nx-plugin): initial commit page generator/schematic
analogjs/analog pull request #577
Opened 2023-07-27 18:22 UTC by luishcastroc

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [x] nx-plugin
- [ ] trpc

## What is the current behavior?

There are no generators for Analog plugin

Closes #565 

## What is the new behavior?

This feature would add the ability to generate pages. It would support Nx Generators and Angular CLI schematics.

Some examples

ng g page about -> src/app/pages/about.page.ts

ng g page blog/post -> src/app/pages/blog/post.page.ts

ng g page products/[products] -> src/app/pages/products/[products].page.ts

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/diQ6sBJYRxN9KXkkpV/giphy.gif"/>

2023-07-28 02:19 UTC, brandonroberts requested changes

2023-07-28 02:19 UTC, brandonroberts commented on packages/nx-plugin/src/generators/page/schema.json
> +      "description": "The path to redirect to.",
```suggestion
      "description": "The page title.",
```

2023-07-28 02:19 UTC, brandonroberts commented on packages/nx-plugin/src/generators/page/schema.json
> +      "description": "The path to redirect to. _Note: This is only needed if the previous prompt is set to true._",
```suggestion
      "description": "The path to redirect to. _Note: This is only needed if the redirect page is set to true._",
```

2023-07-28 02:19 UTC, brandonroberts commented on pnpm-lock.yaml
> -      '@jridgewell/trace-mapping': 0.3.17
Revert the changes to this file

2023-07-28 02:19 UTC, brandonroberts commented on packages/nx-plugin/src/generators/page/schema.json
> +    "name": {
I think this should be `path` or `pathname`. It represents the URL path to the page.

2023-07-31 01:55 UTC, brandonroberts approved these changes

2023-07-31 12:31 UTC, luishcastroc commented
should i complete this one with the blog and post generators? or should we merge it like this and continue in a different complementary feature @brandonroberts

2023-07-31 12:38 UTC, brandonroberts commented
@luishcastroc let's merge this as-is and do the blog support separately. Also need to add some docs for using the generators/schematics

2023-07-31 12:41 UTC, luishcastroc commented
Got it let me work on that and finish those with documentation so we can have everything in place

2023-07-31 12:59 UTC, merged