docs(router): add examples of API routes
analogjs/analog pull request #610
Opened 2023-08-23 17:55 UTC by deepakrudrapaul

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #599 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

2023-08-23 18:12 UTC, markostanimirovic requested changes

2023-08-23 18:12 UTC, markostanimirovic commented on apps/docs-app/docs/features/api/overview.md
> +Routes can use dynamic parameters within brackets in the file name like `/api/hello/[name].ts` and be accessed via event.context.params.
```suggestion
Dynamic API routes are defined by using the filename as the route path enclosed in square brackets. Parameters can be accessed via `event.context.params`.
```

2023-08-23 18:12 UTC, markostanimirovic commented on apps/docs-app/docs/features/api/overview.md
> +File names can be suffixed with .get, .post, .put, .delete, ... to match request's HTTP Method.
```suggestion
File names can be suffixed with `.get`, `.post`, `.put`, `.delete`, etc. to match the specific HTTP request method.
```

2023-08-23 22:08 UTC, markostanimirovic approved these changes

2023-08-24 00:43 UTC, brandonroberts approved these changes

2023-08-24 00:43 UTC, merged

2023-08-24 00:44 UTC, brandonroberts commented
Thanks! @allcontributors add @deepakrudrapaul for doc