fix(create-analog): fixes postcss.config.cjs issue
analogjs/analog pull request #943
Opened 2024-03-15 04:20 UTC by pavankjadda

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

2024-03-15 13:38 UTC, yousefalaqra commented on packages/create-analog/index.js
> -    'postcss.config.js',
Do you need to change this part as well?

function addTailwindConfig(write, filesDir) {
  write(
    'tailwind.config.js',
    fs.readFileSync(path.join(filesDir, `tailwind.config.js`), 'utf-8')
  );
}

2024-03-15 15:14 UTC, brandonroberts requested changes

2024-03-15 15:14 UTC, brandonroberts commented on packages/create-analog/index.js
>      fs.readFileSync(path.join(filesDir, `postcss.config.js`), 'utf-8')
```suggestion
    fs.readFileSync(path.join(filesDir, `postcss.config.cjs`), 'utf-8')
```

2024-03-15 15:14 UTC, brandonroberts commented on packages/create-analog/index.js
>      fs.readFileSync(path.join(filesDir, `tailwind.config.js`), 'utf-8')
```suggestion
    fs.readFileSync(path.join(filesDir, `tailwind.config.cjs`), 'utf-8')
```

2024-03-19 00:33 UTC, brandonroberts approved these changes

2024-03-19 00:34 UTC, merged

2024-03-19 00:35 UTC, brandonroberts commented
Thanks! @allcontributors add @pavankjadda for code